### ISSUE TITLE
Hey is this library still under development?

### ISSUE THREAD

**Issue by Mqxx** [Denoed/Serial#1]
Hey my name is Max. My friend and I are currently also working on a serial library for Deno. We have seen that the last update in this repository was 8 months ago. I'm not sure if this library is still actively under development, so I'm asking if we could get the namespace of the deno module. Otherwise we would have to take another name, which would be unattractive. You're welcome to get back to us about how it looks.

**Comment by IHateYourCode** [comment]
Thank you for reminding me to update this,
I didn't have time in the last months, ..

It's still in development, yes.

No, I don't want to give up the module name,
however if you want to collaborate on lib dev
let me know.

**Comment by Mqxx** [comment]
Hey thanks for the reply. 

I took a look into your code base and I don't really understand what you are doing with a lot of the files/functions. 
I think that it is not really advisable to start a collaboration, because our target groups are just different. We were more interested in the module name as the library we are currently developing is much more complex. 

Additionally we support not only Linux but also other operating systems like Windows and MacOS. 

Furthermore, the Dynamic Link Library and the Shared Object Library are built automatically and the user can use them directly. Also, we only use TypeScript to avoid possible bugs.

If you decide to change your thoughts, you are welcome to contact us by creating a [new issue](https://github.com/TypeScriptPlayground/Serial/issues/new).

Greetings Mqx.

**Comment by IHateYourCode** [comment]
Sure, suit yourself.

Btw, you say you **are** supporting Linux and 
MacOS, however your code says otherwise?

```ts
      case 'linux':
      case 'darwin':
      case 'freebsd':
      case 'netbsd':
      case 'aix':
      case 'solaris':
      case 'illumos': {
          throw new Error(
              `There is currently no implementation for this operating system.
              We are currently working on an implementation for all missing operating systems.
              Current stage:

              - Windows (implemented)
              - Linux (in progress)
              - MacOS (planned)
              
              For more information feel free to check out the repository:
              https://github.com/TypeScriptPlayground/Serial`
          );
      }
```

**Comment by Mqxx** [comment]
C++ code is already done. We have a Compatibility section in the README where you can see that it is under development. The code is only one step away from being Linux compatible.
