### ISSUE TITLE
will there be windows support ?

### ISSUE THREAD

**Issue by Katze719** [Denoed/Serial#2]

**Comment by IHateYourCode** [comment]
I'm not opposed to it, however as I'm *not a Windows user anymore* 
and as such not in the space nor with a setup to do this work I will
\- at least myself \- focus on Linux for now.

If you have experience or knowledge in this 
area I would encourage you to contribute it!

**Comment by Katze719** [comment]
will there be at least support for different c++ compilers ?

**Comment by Katze719** [comment]
wouldn't cmake make more sense for compiling, then a Compile.sh ? and I think the name serial_linux (or something similar) would make more sense.

I feel like naming it Serial is quite confusing for someone like me coming from Windows

**Comment by IHateYourCode** [comment]
1. I don't like using CMake, the shell script just uses GCC
2. `serial_linux` for the shell script?
3. Naming what part `Serial` is confusing to you?
   ( You previously talked about compiliation so I'm not quite sure what you are referring to )

**Comment by Katze719** [comment]
i was just looking for a Serial module at the deno third party modules, and i was hoping for windows support, with serial_linux i would have known faster

**Comment by IHateYourCode** [comment]
Well wouldn't you be searching for `serial_windows` then?

With the next release the description should update 
and - for now - say that the module is Linux specific.

**Comment by Katze719** [comment]
i was also looking for serial_windows after looking for Serial, with an updated description Im happy.
